# Generated by Django 2.2.20 on 2021-04-09 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('acac79e4-c7cc-4e5f-ac0c-fc6f284f7848'), editable=False, primary_key=True, serialize=False),
        ),
    ]
