# Generated by Django 2.2.20 on 2021-04-10 01:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210409_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8bea8de1-182a-4cb7-ab81-5ddb17ccaff9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
