# Generated by Django 2.2.20 on 2021-04-10 01:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210410_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f53f16f6-bf58-452e-beb4-3ea06401da08'), editable=False, primary_key=True, serialize=False),
        ),
    ]
