# Generated by Django 2.2.20 on 2021-04-10 01:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210410_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f1aa894f-a4e5-4e30-9248-75f4ea21c984'), editable=False, primary_key=True, serialize=False),
        ),
    ]
