# Generated by Django 2.2.20 on 2021-04-10 03:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210410_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='created_on',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1ec1eba3-ecdd-47cc-86ac-93edd4a605b5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
